### ISSUE TITLE
does not start with org.freedesktop.Platform.VAAPI.Intel.i386 23.08

### ISSUE THREAD

**Issue by tastytea** [flathub/io.github.sharkwouter.Minigalaxy#61]
i'm getting this error with io.github.sharkwouter.Minigalaxy 1.3.0 and org.freedesktop.Platform.VAAPI.Intel.i386 23.08:

```shellsession
% MG_DEBUG=1 flatpak run io.github.sharkwouter.Minigalaxy
bwrap: Can't mkdir parents for /app/lib/i386-linux-gnu/dri/intel-vaapi-driver: Read-only file system
error: ldconfig failed, exit status 256
```

uninstalling org.freedesktop.Platform.VAAPI.Intel.i386 23.08 and installing 22.08 instead fixes the problem

**Comment by Summertime** [comment]
Confirming the issue and the workaround:

```
flatpak install flatpak runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/22.08
flatpak uninstall runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/23.08
```

Since vaapi gets force installed, its not practical to mask out either.

I think this might be either due to a conflicting extension or a lack of a needed extension, can't tell which though but that seems to be the main cause for most bwrap mkdir errors suffered by others

Similar but different: 

* https://github.com/flathub/net.lutris.Lutris/issues/61
* https://forums.lutris.net/t/steam-deck-missing-vulkan-libraries-after-update-to-0-5-13-flatpak/18240

But unsure of exactly which knobs to turn.

**Comment by Unrud** [comment]
The issue is that **org.gnome.Platform.Compat.i386** is missing the folder _/dri/intel-vaapi-driver_ that is configured as the mount point for **org.freedesktop.Platform.VAAPI.Intel**.

As a workaround you can the folder:
```shell
sudo mkdir /var/lib/flatpak/runtime/org.gnome.Platform.Compat.i386/x86_64/46/active/files/dri
sudo mkdir /var/lib/flatpak/runtime/org.gnome.Platform.Compat.i386/x86_64/46/active/files/dri/intel-vaapi-driver
```
